version: "2"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    user: ${CURRENT_ID}
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "docker/influxdb/env.influxdb"
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb:Z
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: ${CURRENT_ID}
    ports:
      - "3000:3000"
    env_file:
      - "docker/grafana/env.grafana"
    links:
      - influxdb
    volumes:
      - ./docker/grafana/data:/var/lib/grafana:Z
      - ./docker/grafana/provisioning:/var/lib/grafana_provisioning:Z
